version: "3"
services:
  nginx:
    container_name: nginx-container
    image: nginx
    restart: always
    environment:
      - NGINX_HOST=mysite.local
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"
    volumes:
      - web_data:/web
      - ./log:/var/log/nginx
      - ./django-nginx.conf:/etc/nginx/conf.d/mysite.template
    depends_on:
      - web

  web:
    container_name: web-container
    build: ./mysite
    image: mysite
    restart: always
    command: uwsgi --ini uwsgi.ini
    volumes:
      - web_data:/web
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings

volumes:
  web_data: